# Generated by Django 2.1.1 on 2019-01-20 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0012_auto_20190120_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('price', models.IntegerField()),
                ('old_price', models.IntegerField()),
                ('date', models.DateField()),
                ('available', models.IntegerField()),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
            ],
        ),
    ]
