# Generated by Django 2.1.1 on 2019-01-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_merge_20190120_1907'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_deck', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('date', models.DateField()),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Card')),
            ],
        ),
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('point', models.IntegerField()),
                ('type', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Store',
            new_name='exchange',
        ),
    ]
