# Generated by Django 2.1.1 on 2019-01-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_store',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
