# Generated by Django 2.1.1 on 2019-01-21 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190121_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchange',
            old_name='old_price',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='price',
        ),
        migrations.AlterField(
            model_name='card_store',
            name='id_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.Deck'),
        ),
        migrations.AlterField(
            model_name='card_store',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
