# Generated by Django 2.1.1 on 2019-01-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_card_store_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_store',
            name='new_field',
        ),
    ]
