# Generated by Django 2.1.1 on 2019-01-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_card_store_new_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
