version: '3'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: hearthstone
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
