# Generated by Django 2.1.1 on 2018-10-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('cost', models.IntegerField()),
                ('attack_point', models.IntegerField()),
                ('life_point', models.IntegerField()),
                ('type_card', models.CharField(blank=True, max_length=10)),
                ('classe', models.CharField(blank=True, max_length=10)),
                ('rare', models.CharField(blank=True, max_length=10)),
                ('race', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
