# Generated by Django 2.1.1 on 2018-10-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_deck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='card',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
