# Generated by Django 2.1.1 on 2018-11-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
