# Generated by Django 2.1.1 on 2018-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
