# Generated by Django 2.1.2 on 2018-12-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_auto_20181113_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='artist',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='card',
            name='cardSet',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='card',
            name='imageGold',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_card',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
