# Generated by Django 2.1.2 on 2018-12-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20181204_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='attack_point',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='life_point',
            field=models.IntegerField(blank=True),
        ),
    ]
