# Generated by Django 2.1.2 on 2018-12-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20181204_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='race',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
