# Generated by Django 2.1.2 on 2019-01-20 10:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_auto_20181204_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='rare',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
