# Generated by Django 2.1.1 on 2019-01-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_auto_20181204_1606'),
        ('card', '0010_auto_20181204_1609'),
    ]

    operations = [
    ]
