# Generated by Django 2.1.1 on 2019-01-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_merge_20190120_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='rare',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
