# Generated by Django 2.1.2 on 2019-01-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20190120_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
