# Generated by Django 2.1.2 on 2019-01-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_collection_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='card_ids',
        ),
        migrations.AddField(
            model_name='collection',
            name='card_id',
            field=models.ManyToManyField(to='card.Card'),
        ),
    ]
