# Generated by Django 2.1.2 on 2019-01-20 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_auto_20190120_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='card_id',
            new_name='cards',
        ),
    ]
