# Generated by Django 2.1.1 on 2019-01-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_auto_20190120_1122'),
        ('card', '0014_auto_20190120_1543'),
    ]

    operations = [
    ]
